<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\countries;

class nationality_info extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('countries')->delete();

        $countries = array(
            array('country_name' => 'Afghanistan','country_code' => '93','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Albania', 'country_code' => '355','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Algeria', 'country_code' => '213','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'American Samoa', 'country_code' => '1684','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Andorra','country_code' => '376','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Angola','country_code' => '244','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Anguilla','country_code' => '1264','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Antarctica','country_code' => '0','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Antigua and Barbuda','country_code' => '1268','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Argentina','country_code' => '54','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Armenia','country_code' => '374','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Aruba','country_code' => '297','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Australia','country_code' => '61','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Austria','country_code' => '43','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Azerbaijan','country_code' => '994','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Bahamas', 'country_code' => '1242','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Bahrain','country_code' => '973','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Bangladesh','country_code' => '880','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Barbados','country_code' => '1246','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Belarus','country_code' => '375','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Belgium', 'country_code' => '32','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Belize','country_code' => '501','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Benin','country_code' => '229','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Bermuda','country_code' => '1441','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Bhutan','country_code' => '975','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Bolivia','country_code' => '591','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Bosnia and Herzegovina','country_code' => '387','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Botswana','country_code' => '267','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Bouvet Island','country_code' => '0','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Brazil','country_code' => '55','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'British Indian Ocean Territory','country_code' => '246','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Brunei Darussalam','country_code' => '673','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Bulgaria','country_code' => '359','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Burkina Faso','country_code' => '226','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Burundi','country_code' => '257','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Cambodia','country_code' => '855','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Cameroon','country_code' => '237','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Canada','country_code' => '124','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Cape Verde','country_code' => '238','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Cayman Islands','country_code' => '1345','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Central African Republic','country_code' => '236','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Chad', 'country_code' => '235','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Chile', 'country_code' => '56','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'China','country_code' => '86','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Christmas Island', 'country_code' => '61','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Cocos (Keeling) Islands', 'country_code' => '672','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Colombia','country_code' => '57','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Comoros','country_code' => '269','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Congo','country_code' => '242','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Democratic Republic of Congo','country_code' => '242','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Cook Islands','country_code' => '682','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Costa Rica','country_code' => '506','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Cote D\'Ivoire','country_code' => '225','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Croatia', 'country_code' => '385','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Cuba','country_code' => '53','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Cyprus','country_code' => '357','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Czech Republic','country_code' => '420','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Denmark', 'country_code' => '45','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Djibouti','country_code' => '253','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Dominica', 'country_code' => '1767','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Dominican Republic','country_code' => '1809','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Ecuador','country_code' => '593','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Egypt', 'country_code' => '20','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'El Salvador','country_code' => '503','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Equatorial Guinea','country_code' => '240','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Eritrea','country_code' => '291','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Estonia','country_code' => '372','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Ethiopia','country_code' => '251','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Falkland Islands (Malvinas)','country_code' => '500','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Faroe Islands','country_code' => '298','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Fiji','country_code' => '679','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Finland','country_code' => '358','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'France','country_code' => '33','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'French Guiana','country_code' => '594','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'French Polynesia','country_code' => '689','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Gabon','country_code' => '241','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Gambia','country_code' => '220','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Georgia','country_code' => '995','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Germany','country_code' => '49','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Ghana','country_code' => '233','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Gibraltar','country_code' => '350','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Greece','country_code' => '30','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Greenland','country_code' => '299','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Grenada','country_code' => '1473','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Guadeloupe','country_code' => '590','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Guam', 'country_code' => '1671','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Guatemala','country_code' => '502','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Guinea','country_code' => '224','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Guinea-Bissau','country_code' => '245','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Guyana','country_code' => '592','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Haiti','country_code' => '509','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Holy See (Vatican City State)','country_code' => '39','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Honduras', 'country_code' => '504','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Hong Kong','country_code' => '852','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Hungary', 'country_code' => '36','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Iceland','country_code' => '354','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'India','country_code' => '91','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Indonesia','country_code' => '62','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Iran','country_code' => '98','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Iraq','country_code' => '964','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Ireland','country_code' => '353','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Israel','country_code' => '972','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Italy','country_code' => '39','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Jamaica','country_code' => '1876','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Japan','country_code' => '81','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Jordan','country_code' => '962','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Kazakhstan','country_code' => '7','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Kenya','country_code' => '254','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Kiribati', 'country_code' => '686','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Democratic Peoples Republic of Korea','country_code' => '850','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Republic of Korea','country_code' => '82','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Kuwait','country_code' => '965','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Kyrgyzstan','country_code' => '996','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Lao People\'s Democratic Republic','country_code' => '856','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Latvia','country_code' => '371','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Lebanon','country_code' => '961','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Lesotho','country_code' => '266','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Liberia','country_code' => '231','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Libyan Arab Jamahiriya','country_code' => '218','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Liechtenstein','country_code' => '423','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Lithuania','country_code' => '370','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Luxembourg', 'country_code' => '352','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Macao','country_code' => '853','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Macedonia','country_code' => '389','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Madagascar','country_code' => '261','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Malawi','country_code' => '265','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Malaysia','country_code' => '60','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Maldives','country_code' => '960','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Mali','country_code' => '223','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Malta','country_code' => '356','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Marshall Islands','country_code' => '692','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Martinique','country_code' => '596','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Mauritania','country_code' => '222','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Mauritius','country_code' => '230','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Mayotte', 'country_code' => '269','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Mexico','country_code' => '52','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Micronesia','country_code' => '691','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Moldova','country_code' => '373','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Monaco','country_code' => '377','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Mongolia','country_code' => '976','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Montserrat','country_code' => '1664','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Morocco','country_code' => '212','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Mozambique','country_code' => '258','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Myanmar','country_code' => '95','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Namibia','country_code' => '264','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Nauru','country_code' => '674','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Nepal','country_code' => '977','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Netherlands','country_code' => '31','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Netherlands Antilles','country_code' => '599','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'New Caledonia','country_code' => '687','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'New Zealand','country_code' => '64','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Nicaragua','country_code' => '505','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Niger','country_code' => '227','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Nigeria','country_code' => '234','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Niue','country_code' => '683','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Norfolk Island','country_code' => '672','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Northern Mariana Islands','country_code' => '1670','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Norway', 'country_code' => '47','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Oman','country_code' => '968','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Pakistan','country_code' => '92','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Palau','country_code' => '680','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Palestinian', 'country_code' => '970','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Panama','country_code' => '507','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Guinea','country_code' => '675','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Paraguay','country_code' => '595','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Peru', 'country_code' => '51','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Philippines', 'country_code' => '63','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Pitcairn','country_code' => '0','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Poland', 'country_code' => '48','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Portugal','country_code' => '351','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Puerto Rico', 'country_code' => '1787','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Qatar','country_code' => '974','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Reunion','country_code' => '262','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Romania','country_code' => '40','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Russia', 'country_code' => '70','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Rwanda','country_code' => '250','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Saint Helena','country_code' => '290','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Saint Kitts and Nevis','country_code' => '1869','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Saint Lucia','country_code' => '1758','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Saint Pierre and Miquelon', 'country_code' => '508','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Saint Vincent and the Grenadines','country_code' => '1784','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Samoa','country_code' => '684','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'San Marino','country_code' => '378','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Sao Tome and Principe','country_code' => '239','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Saudi Arabia','country_code' => '966','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Senegal','country_code' => '221','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Serbia and Montenegro', 'country_code' => '381','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Seychelles', 'country_code' => '248','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Sierra Leone','country_code' => '232','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Singapore', 'country_code' => '65','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Slovakia','country_code' => '421','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Slovenia','country_code' => '386','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Solomon Islands','country_code' => '677','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Somalia', 'country_code' => '252','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'South Africa','country_code' => '27','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'South Georgia and the South Sandwich Islands', 'country_code' => '500','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Spain','country_code' => '34','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Sri Lanka','country_code' => '94','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Sudan','country_code' => '249','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Suricountry_name','country_code' => '597','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Svalbard and Jan Mayen','country_code' => '47','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Swaziland','country_code' => '268','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Sweden','country_code' => '46','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Switzerland', 'country_code' => '41','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Syrian Arab Republic','country_code' => '963','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Taiwan','country_code' => '886','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Tajikistan','country_code' => '992','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Tanzanian','country_code' => '255','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Thailand','country_code' => '66','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Timor-Leste', 'country_code' => '670','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Togo','country_code' => '228','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Tokelau','country_code' => '690','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Tonga','country_code' => '676','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Trinidad and Tobago','country_code' => '1868','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Tunisia','country_code' => '216','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Turkey','country_code' => '90','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Turkmenistan','country_code' => '7370','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Turks and Caicos Islands','country_code' => '1649','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Tuvalu', 'country_code' => '688','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Uganda','country_code' => '256','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Ukraine','country_code' => '380','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'United Arab Emirates','country_code' => '971','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'United Kingdom','country_code' => '44','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'United States','country_code' => '1','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Uruguay','country_code' => '598','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Uzbekistan','country_code' => '998','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Vanuatu','country_code' => '678','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Venezuela','country_code' => '58','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Viet Nam','country_code' => '84','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Virgin Islands, British','country_code' => '1284','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Virgin Islands, U.s.','country_code' => '1340','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Wallis and Futuna','country_code' => '681','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Western Sahara','country_code' => '212','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Yemen','country_code' => '967','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Zambia', 'country_code' => '260','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Zimbabwe', 'country_code' => '263','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Serbia','country_code' => '381','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Montenegro','country_code' => '382','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Aland Islands','country_code' => '358','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Bonaire','country_code' => '599','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Curacao','country_code' => '599','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Guernsey','country_code' => '44','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Isle of Man','country_code' => '44','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Jersey', 'country_code' => '44','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Kosovo','country_code' => '381','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Saint Barthelemy','country_code' => '590','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Saint Martin','country_code' => '590','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'Sint Maarten','country_code' => '721','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()),
            array('country_name' => 'South Sudan','country_code' => '211','created_by' => '1', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now())
          );

          DB::table('countries')->insert($countries);
    }
    
}
